services:
  app:
    container_name: app
    build:
      dockerfile: dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://postgres:admin@localhost:5432/dev_db
    ports:
      - 3000:3000
    volumes:
      - ./app:/go/src/app
    depends_on:
      - example_db

  example_db:
    container_name: example_db
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5435:5432
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db_data:/var/lib/postgresql/data
